### ISSUE TITLE
Using codyframe with React

### ISSUE THREAD

**Issue by Oliversoftwaresolutions** [codyhouse/codyframe#1]
Hey Guys,

I'm trying to use codyframe with React. I'm trying to follow all the steps given, but i don't really understand how to get it working the steps are not very clear. If anyone has managed to get it working could you please send me a guide or give me a helping hand. Thank you very much.

**Comment by claudia-romano** [comment]
Hi Oliver, could you provide more info on the issues you are experiencing and the steps that are not clear? For example, did you try importing the css files of the framework or the scss? Thanks.

**Comment by Oliversoftwaresolutions** [comment]
Hi Claudia, I tried import the CSS files and. when I tired using the ReadMore component in the docs and importing the JS inside the component it was not importing into the DOM and keeps have an unexpected error '<' on line 1. The Docs are not very clear to me. I installed codyframe with NPM and referenced the CSS files in my CSS but it does not work all I see is the HTML instead the CSS and JavaScript.

**Comment by claudia-romano** [comment]
Hi Oliver, sorry but I'm not sure I got your issue. You were able to successfully import the framework, is that correct?

If you imported the framework, then please try importing the component one step at a time. First the HTML (make sure it is properly rendered), then the CSS and finally the JS. 

If you get an error when importing the JS, then you are probably using the wrong url for the component JS (the `frontEnd.src` value depends on your project so make sure to update it). This should fix your issue.

**Comment by Oliversoftwaresolutions** [comment]
Hi Claudia, I copied the example on the docs with the ReadMore component. and The css was loading in fine. It's the JS i keep having issues with. I keep getting the same error which is "unexpected error < line 1" I also made sure to change the frontEnd.src to match my URL.

**Comment by claudia-romano** [comment]
Hi Oliver, can you check and see if the `<script>` is appended to the HTML and the file is found? 
Also, which is the line 1 the error refers to? Thanks.

**Comment by Oliversoftwaresolutions** [comment]
Hi Claudia,

I can see in the HTML that the file is appended in the script tag. But it does not appear in the sources tab inside chrome inspect. I found out if I change the type to in the script tag to type="babel/JavaScript" the error disappears but still does not work. I've followed your docs to the letter but still keep running into the same issue. Thanks

**Comment by claudia-romano** [comment]
Hi Oliver, could you add a console.log to the JS file of the component? This way you can check if you see the log message in the console. If you don't, then the JS file is not found at the path specified. Thanks!

**Comment by claudia-romano** [comment]
I'm closing this as no additional details were provided. Feel free to reopen it if you are still experiencing the same issue. Thanks!
