### ISSUE TITLE
compress css and js for production

### ISSUE THREAD

**Issue by matobeag** [codyhouse/codyframe#2]
hi
Is it possible to reinstate the "gulp dist" command or is there an alternative method for compressing my CSS/JS files for production?

**Comment by claudia-romano** [comment]
Hi there, the `dist` task included in codyframe v3 works regardless of the framework, so you can use the same for codyframe v4.

**Comment by matobeag** [comment]
In the latest version of CodyFrame, is it ok to change the order of utility imports in the style.scss file?

Original order:
```
@use 'typography';
@use 'icons';
@use 'buttons';
@use 'forms';
@use 'components/**/*.scss';
@use '../../node_modules/codyframe/main/scss/util';
```
Modified order:
```
@use '../../node_modules/codyframe/main/scss/util';
@use 'typography';
@use 'icons';
@use 'buttons';
@use 'forms';
@use 'components/**/*.scss';
```

Otherwise the /*! purgecss start ignore */ and /*! purgecss end ignore */ comments somehow encompass all components and styles, and purgeCSS will become ineffective.

**Comment by claudia-romano** [comment]
Hi there, you cannot modify the order, utilities should be imported at the end.

As for the purge, you should not use it for the components. Some of the component classes are used in JS (defined dynamically) so purge may break them. This is the reason why we add the purgecss start/purge end comments, to make sure only utility classes are properly cleaned. This is the same logic we used in CodyFrame v3.

Please also note that the components only have the classes required for them to work properly, so there should be no need to clean them with purgeCSS.
