### ISSUE TITLE
password component, missing file

### ISSUE THREAD

**Issue by TeaEwan** [codyhouse/codyframe#5]
url: [https://codyhouse.co/ds/components/app/password-visibility-control--icon](https://codyhouse.co/ds/components/app/password-visibility-control--icon)

In the downloaded zip file, there is no “_1_password.css” and “_1_password.js”.

<img width="361" alt="image" src="https://github.com/codyhouse/codyframe/assets/93706123/783b59fb-946b-456c-98c8-a6374714d937">

**Comment by claudia-romano** [comment]
Thanks for the heads-up! This should be fixed now.
